name: 🚀 Deploy to cPanel

on:
  push:
    branches:
      - main  # Replace with your default branch (e.g., master)

jobs:
  deploy:
    name: 🎉 Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: 📂 Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /  # Target directory on cPanel (adjust as needed)
          # Optional: Exclude files like Git metadata
          exclude: |
            **/.git*
            **/.git*/**
